### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by pvlb** [inbasic/ignotifier#299]
Need zoom font body messages.
Is it possible with the help of extension stylish increase font size?

**Comment by inbasic** [comment]
Yes it is possible. Here is a sample
```css
@-moz-document url("resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/ignotifier/data/popup/index.html") {
  #content {
   font-size: 17px;
  }
}
```

The `-moz-document` is used to limit your changes to the popup element. In this example, I changed the font size of the entire panel, however you can change each elements separately as well. Find elements from:
https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/data/popup/index.css
